# Generated by Django 3.2.6 on 2021-08-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.TextField()),
                ('replier', models.CharField(max_length=32)),
                ('creator', models.CharField(max_length=32)),
                ('create_time', models.DateField()),
            ],
        ),
    ]
