# Generated by Django 3.2 on 2021-08-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210818_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddr',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='ddr',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='ddr',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='package',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='package',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='package',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='create_time',
            field=models.DateField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='creator',
            field=models.CharField(max_length=32, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='replier',
            field=models.CharField(max_length=32, verbose_name='回复人'),
        ),
    ]
