# Generated by Django 3.2 on 2021-08-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210818_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddr',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='package',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='create_time',
            field=models.DateField(null=True, verbose_name='创建时间'),
        ),
    ]
