# Generated by Django 3.2 on 2021-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210819_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddr',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='ddr',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='dp',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='hdmi',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='mipi',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='package',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='package',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='package',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='pll',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='saradc',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='serdes',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='tvsensor',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='u2',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='u3',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='answers',
            field=models.TextField(null=True, verbose_name='回复'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='creator',
            field=models.CharField(max_length=32, null=True, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='vdac',
            name='replier',
            field=models.CharField(max_length=32, null=True, verbose_name='回复人'),
        ),
    ]
